model:
  base_learning_rate: 2.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: hybrid
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    use_ema: true
    x_feat_extracted: true
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [1000]
        cycle_lengths: [10000000000000]
        f_start: [1.0e-06]
        f_max: [1.0]
        f_min: [1.0]
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: true
        use_fp16: true
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions: [8, 4, 2]
        num_res_blocks: 2
        channel_mult: [1, 2, 3, 5]
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
        ckpt_path: ""  # Leave empty for Colab; weights loaded dynamically
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.EmbeddingViT2_5
      params:
        feat_key: ssl_feat
        mag_key: mag
        num_layers: 12
        input_channels: 1024
        hidden_channels: 512
        vit_mlp_dim: 2048
        p_uncond: 0.1
# Data module is optional in Colab; we load datasets dynamically
# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 4
#     num_workers: 2
#     wrap: false
#     train:
#       target: ldm.data.brca.TCGADataset
#       params:
#         config:
#           root: ""
#           normalize_ssl: true
#           feat_target_size: 8
